-- Create contact_us table
create table if not exists public.contact_us (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  subject text,
  message text,
  status text default 'new' -- new, read, replied
);

-- Enable RLS
alter table public.contact_us enable row level security;

-- Policies (assuming admin interaction via service role or authenticated admin user)
-- For now allowing public insert (for frontend contact form) and service role full access
create policy "Allow public insert" on public.contact_us
  for insert with check (true);

create policy "Allow service role full access" on public.contact_us
  using (auth.role() = 'service_role');
