-- Create email_logs table
create table if not exists email_logs (
  id bigint generated by default as identity primary key,
  member_id uuid references members(id) on delete set null,
  email_to text not null,
  subject text not null,
  message text not null,
  category text not null, -- 'activation', 'deposit', 'withdraw', 'general'
  status text default 'sent', -- 'sent', 'failed'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
